---
abstract: 'Improvements to the build in reminder function'
author:
  - 'Christian Loos <cloos@netcologne.de>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ReminderImproved
no_index:
  directory:
    - html
    - inc
    - po
  package:
    - RT::Reminders
    - RT::Ticket
requires:
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/cloos/RT-Extension-ReminderImproved
version: 0.07
x_module_install_rtx_version: 0.36
x_requires_rt: 3.8.0
x_rt_too_new: 4.0.0
